/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWitnessesRouteImport } from './routes/dashboard.witnesses'
import { Route as DashboardTimelineRouteImport } from './routes/dashboard.timeline'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMemoryRouteImport } from './routes/dashboard.memory'
import { Route as DashboardLiveRouteImport } from './routes/dashboard.live'
import { Route as DashboardIngestRouteImport } from './routes/dashboard.ingest'
import { Route as DashboardEvidenceRouteImport } from './routes/dashboard.evidence'
import { Route as DashboardContradictionsRouteImport } from './routes/dashboard.contradictions'
import { Route as DashboardCasesRouteImport } from './routes/dashboard.cases'
import { Route as DashboardAskRouteImport } from './routes/dashboard.ask'
import { Route as ApiPublicCogneeCheckRouteImport } from './routes/api/public/cognee-check'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWitnessesRoute = DashboardWitnessesRouteImport.update({
  id: '/witnesses',
  path: '/witnesses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimelineRoute = DashboardTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoryRoute = DashboardMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIngestRoute = DashboardIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvidenceRoute = DashboardEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContradictionsRoute = DashboardContradictionsRouteImport.update({
  id: '/contradictions',
  path: '/contradictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesRoute = DashboardCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAskRoute = DashboardAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicCogneeCheckRoute = ApiPublicCogneeCheckRouteImport.update({
  id: '/api/public/cognee-check',
  path: '/api/public/cognee-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/contradictions': typeof DashboardContradictionsRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/memory': typeof DashboardMemoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/witnesses': typeof DashboardWitnessesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cognee-check': typeof ApiPublicCogneeCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/contradictions': typeof DashboardContradictionsRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/memory': typeof DashboardMemoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/witnesses': typeof DashboardWitnessesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/cognee-check': typeof ApiPublicCogneeCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/contradictions': typeof DashboardContradictionsRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/memory': typeof DashboardMemoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/witnesses': typeof DashboardWitnessesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cognee-check': typeof ApiPublicCogneeCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ask'
    | '/dashboard/cases'
    | '/dashboard/contradictions'
    | '/dashboard/evidence'
    | '/dashboard/ingest'
    | '/dashboard/live'
    | '/dashboard/memory'
    | '/dashboard/settings'
    | '/dashboard/timeline'
    | '/dashboard/witnesses'
    | '/dashboard/'
    | '/api/public/cognee-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ask'
    | '/dashboard/cases'
    | '/dashboard/contradictions'
    | '/dashboard/evidence'
    | '/dashboard/ingest'
    | '/dashboard/live'
    | '/dashboard/memory'
    | '/dashboard/settings'
    | '/dashboard/timeline'
    | '/dashboard/witnesses'
    | '/dashboard'
    | '/api/public/cognee-check'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ask'
    | '/dashboard/cases'
    | '/dashboard/contradictions'
    | '/dashboard/evidence'
    | '/dashboard/ingest'
    | '/dashboard/live'
    | '/dashboard/memory'
    | '/dashboard/settings'
    | '/dashboard/timeline'
    | '/dashboard/witnesses'
    | '/dashboard/'
    | '/api/public/cognee-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPublicCogneeCheckRoute: typeof ApiPublicCogneeCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/witnesses': {
      id: '/dashboard/witnesses'
      path: '/witnesses'
      fullPath: '/dashboard/witnesses'
      preLoaderRoute: typeof DashboardWitnessesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timeline': {
      id: '/dashboard/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardTimelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memory': {
      id: '/dashboard/memory'
      path: '/memory'
      fullPath: '/dashboard/memory'
      preLoaderRoute: typeof DashboardMemoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ingest': {
      id: '/dashboard/ingest'
      path: '/ingest'
      fullPath: '/dashboard/ingest'
      preLoaderRoute: typeof DashboardIngestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evidence': {
      id: '/dashboard/evidence'
      path: '/evidence'
      fullPath: '/dashboard/evidence'
      preLoaderRoute: typeof DashboardEvidenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contradictions': {
      id: '/dashboard/contradictions'
      path: '/contradictions'
      fullPath: '/dashboard/contradictions'
      preLoaderRoute: typeof DashboardContradictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases': {
      id: '/dashboard/cases'
      path: '/cases'
      fullPath: '/dashboard/cases'
      preLoaderRoute: typeof DashboardCasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ask': {
      id: '/dashboard/ask'
      path: '/ask'
      fullPath: '/dashboard/ask'
      preLoaderRoute: typeof DashboardAskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/cognee-check': {
      id: '/api/public/cognee-check'
      path: '/api/public/cognee-check'
      fullPath: '/api/public/cognee-check'
      preLoaderRoute: typeof ApiPublicCogneeCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAskRoute: typeof DashboardAskRoute
  DashboardCasesRoute: typeof DashboardCasesRoute
  DashboardContradictionsRoute: typeof DashboardContradictionsRoute
  DashboardEvidenceRoute: typeof DashboardEvidenceRoute
  DashboardIngestRoute: typeof DashboardIngestRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardMemoryRoute: typeof DashboardMemoryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTimelineRoute: typeof DashboardTimelineRoute
  DashboardWitnessesRoute: typeof DashboardWitnessesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAskRoute: DashboardAskRoute,
  DashboardCasesRoute: DashboardCasesRoute,
  DashboardContradictionsRoute: DashboardContradictionsRoute,
  DashboardEvidenceRoute: DashboardEvidenceRoute,
  DashboardIngestRoute: DashboardIngestRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardMemoryRoute: DashboardMemoryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTimelineRoute: DashboardTimelineRoute,
  DashboardWitnessesRoute: DashboardWitnessesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPublicCogneeCheckRoute: ApiPublicCogneeCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
